// Mensagens i18n do modulo "sync". Dono: agente C (Sincronizar: sync).
// Cada agente acrescenta chaves SO no(s) proprio(s) modulo(s); o agregador e src/i18n/messages.ts.
import type { Message } from "./types";

export const SYNC_MESSAGES = {
  "sync.title": { pt: "Sincronizar entre dispositivos", en: "Sync between devices" },
  "sync.generate": { pt: "Gerar código", en: "Generate code" },
  "sync.receive": { pt: "Receber código", en: "Receive code" },
  "sync.copy": { pt: "Copiar código", en: "Copy code" },
  "sync.copied": { pt: "Código copiado", en: "Code copied" },
  "sync.paste": { pt: "Colar código", en: "Paste code" },
  "sync.scan": { pt: "Ler QR pela câmera", en: "Scan QR with camera" },
  "sync.file": { pt: "Abrir arquivo", en: "Open file" },
  "sync.merge": { pt: "Mesclar", en: "Merge" },
  "sync.replace": { pt: "Substituir", en: "Replace" },
  "sync.cancel": { pt: "Cancelar", en: "Cancel" },
  "sync.summary": { pt: "Resumo do código recebido", en: "Received code summary" },
  "sync.frames": { pt: "Frame {n} de {total}", en: "Frame {n} of {total}" },
  "sync.missingFrames": { pt: "Faltam {n} frames", en: "{n} frames missing" },
  "sync.otherSession": { pt: "Este frame é de outro código; continue lendo os frames do mesmo código ou recomece.", en: "This frame belongs to another code; keep scanning frames of the same code or start over." },
  "sync.unsupportedVersion": { pt: "Este código foi gerado por uma versão mais nova do Pontindex. Atualize o app.", en: "This code was generated by a newer version of Pontindex. Update the app." },
  "sync.corrupted": { pt: "Código inválido ou corrompido. Confira se copiou tudo.", en: "Invalid or corrupted code. Check that you copied all of it." },
  "sync.oversized": { pt: "Código grande demais para ser um código do Pontindex.", en: "Code too large to be a Pontindex code." },
  "sync.foreignApp": { pt: "Isso não parece um código do Pontindex.", en: "This does not look like a Pontindex code." },
  "sync.empty": { pt: "Cole um código para continuar.", en: "Paste a code to continue." },
  "sync.orphans": { pt: "{n} registros de outra versão do dataset (mantidos, não exibidos)", en: "{n} records from another dataset version (kept, not shown)" },
  "sync.cameraUnavailable": { pt: "Câmera indisponível", en: "Camera unavailable" },
  "sync.applied": { pt: "Dados sincronizados", en: "Data synced" },
} as const satisfies Record<string, Message>;
