// Icones de UI: lucide-react com versao fixa (sem CDN). Reexporta so os usados, para tree-shaking.
// Nomes do prototipo (data-lucide="...") em PascalCase.
export {
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  Backpack,
  Box,
  Camera,
  Check,
  ChevronDown,
  CircleDot,
  Cloud,
  Copy,
  CornerDownRight,
  Download,
  Ellipsis,
  Heart,
  HeartPulse,
  House,
  Info,
  Languages,
  Lightbulb,
  List,
  MapPin,
  Moon,
  MousePointerClick,
  Package,
  Palette,
  Plus,
  QrCode,
  RotateCcw,
  Search,
  Settings,
  Shield,
  SlidersHorizontal,
  Sparkle,
  Sparkles,
  Star,
  Sun,
  Swords,
  Target,
  Trash2,
  Upload,
  Volume2,
  VolumeX,
  X,
  Zap,
} from "lucide-react";
export type { LucideIcon, LucideProps } from "lucide-react";
